version: '3.9'

services:
  redis:
    image: redis:7.2.1-alpine
    container_name: redis-server
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  redis-data:
    name: redis-storage
